import { useContext, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AudioLines, ArrowRight } from 'lucide-react';
import { AuthContext } from '../context/AuthContext';
import { Button, ErrorState } from './ui';
export default function AuthPage({ registerMode = false }) {
  const {login,register} = useContext(AuthContext);
  const navigate = useNavigate();
  const [name,setName] = useState(''),[email,setEmail] = useState(''),[password,setPassword] = useState(''),[error,setError] = useState(''),[busy,setBusy] = useState(false);
  const submit = async e => { e.preventDefault(); setError(''); setBusy(true); try { if(registerMode) await register(name,email,password); else await login(email,password); navigate('/dashboard'); } catch(err) { setError(err.response?.data?.message || 'We couldn’t sign you in. Please try again.'); } finally { setBusy(false); } };
  return <div className="auth-page"><aside className="auth-story"><div className="brand"><span className="brand-icon"><AudioLines size={23}/></span>Interview<span className="brand-iq">IQ</span></div><div><p className="eyebrow">PREPARE WITH PURPOSE</p><h2>Walk into your next interview with confidence.</h2><p className="muted">Practice thoughtful answers. Understand your strengths. Know exactly what to work on next.</p><div className="auth-steps"><div className="auth-step"><span>01</span><strong>Practice for the role you want</strong></div><div className="auth-step"><span>02</span><strong>Get clear, structured feedback</strong></div><div className="auth-step"><span>03</span><strong>Turn insights into progress</strong></div></div></div><footer>Your preparation. Your pace. Your next opportunity.</footer></aside><main className="auth-form-area"><div className="auth-form"><div className="mobile-brand">InterviewIQ</div><p className="eyebrow">YOUR CAREER, ONE STEP FORWARD</p><h1>{registerMode ? 'Create your account' : 'Welcome back'}</h1><p className="muted">{registerMode ? 'Make room for your next opportunity.' : 'Pick up your preparation where you left off.'}</p>{error && <div className="mt-5"><ErrorState message={error}/></div>}<form onSubmit={submit}>{registerMode && <div className="field"><label htmlFor="auth-name">Full name</label><input id="auth-name" autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name" /></div>}<div className="field"><label htmlFor="auth-email">Email address</label><input id="auth-email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com" /></div><div className="field"><label htmlFor="auth-password">Password</label><input id="auth-password" type="password" autoComplete={registerMode?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} required minLength={registerMode?6:undefined} aria-describedby={registerMode?'password-help':undefined}/>{registerMode && <small id="password-help">Use at least 6 characters.</small>}</div><Button type="submit" busy={busy}>{busy ? (registerMode?'Creating account…':'Signing in…') : (registerMode?'Create account':'Sign in')}<ArrowRight size={16}/></Button></form><p className="auth-switch">{registerMode?'Already have an account?':'New to InterviewIQ?'} <Link to={registerMode?'/login':'/register'}>{registerMode?'Sign in':'Create an account'}</Link></p></div></main></div>;
}

