import { useCallback, useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowRight, Play, Send, CheckCircle2 } from 'lucide-react';
import * as interviewService from '../../services/interviewService';
import { Card, PageHeader, Button, ButtonLink, Badge, LoadingState, ErrorState, Evaluation } from '../../components/ui';
export default function InterviewRoom() {
  const {sessionId}=useParams(),navigate=useNavigate();
  const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[generating,setGenerating]=useState(false),[submitting,setSubmitting]=useState(false),[completing,setCompleting]=useState(false),[index,setIndex]=useState(0),[answerText,setAnswerText]=useState(''),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await interviewService.getSession(sessionId);if(data.status==='completed'){navigate(`/interview/${sessionId}/results`,{replace:true});return;}setSession(data);if(data.questions?.length){const next=data.questions.findIndex(q=>!q.userAnswer);setIndex(next>=0?next:data.questions.length-1);}}catch{setError('We couldn’t load this interview.');}finally{setLoading(false);}},[sessionId,navigate]);
  useEffect(()=>{load();},[load]);
  const generate=async()=>{setGenerating(true);setError('');try{setSession(await interviewService.generateQuestions(sessionId));setIndex(0);}catch(err){setError(err.response?.data?.message||'Failed to generate questions');}finally{setGenerating(false);}};
  const submit=async e=>{e.preventDefault();if(!answerText.trim()||submitting)return;setSubmitting(true);setError('');try{const result=await interviewService.submitAnswer(sessionId,session.questions[index]._id,answerText);setSession(prev=>({...prev,questions:prev.questions.map(q=>q._id===result.question._id?result.question:q)}));setAnswerText('');}catch(err){setError(err.response?.data?.message||'Failed to submit answer');}finally{setSubmitting(false);}};
  const finish=async()=>{if(completing)return;setCompleting(true);setError('');try{await interviewService.completeSession(sessionId);navigate(`/interview/${sessionId}/results`);}catch(err){setError(err.response?.data?.message||'Failed to complete session');setCompleting(false);}};
  if(loading)return <LoadingState label="Preparing your interview workspace…"/>;
  if(!session)return <ErrorState message={error||'Session not found'} retry={load}/>;
  const questions=session.questions||[],q=questions[index];
  if(session.status==='created'&&!questions.length)return <div className="narrow"><PageHeader eyebrow="A LITTLE PRACTICE GOES A LONG WAY" title="Ready when you are" description="Take a breath. Give each question your best thinking."/><Card className="stack"><div className="icon-tile"><Play size={22}/></div><div><h2>{session.targetRole}</h2><div className="chips mt-3"><Badge tone="primary">{session.interviewMode}</Badge><Badge>{session.difficulty}</Badge><Badge>{session.questionCount} questions</Badge></div></div><p className="muted">You'll answer one question at a time, review your feedback, and choose when to move on.</p>{error&&<ErrorState message={error}/>}<div><Button onClick={generate} busy={generating}>{generating?'Generating your questions…':'Start Interview'}<ArrowRight size={16}/></Button></div></Card></div>;
  if(!q)return <ErrorState message="No questions are available in this session." retry={load}/>;
  const answered=!!q.userAnswer;
  return <div className="narrow"><PageHeader eyebrow={session.interviewMode} title={session.targetRole} description="A focused space to think, answer and improve."/><div className="progress-header"><span>Question {index+1} of {questions.length}</span><span>{questions.filter(item=>item.userAnswer).length} answered</span></div><progress className="progress-bar mb-6" value={index+1} max={questions.length} aria-label="Question progress"/>{error&&<ErrorState message={error}/>}<div className="stack"><Card className="question-card"><div className="chips"><Badge tone="primary">Question {String(index+1).padStart(2,'0')}</Badge><Badge>{q.topic}</Badge><Badge>{q.difficulty}</Badge></div><h2 className="question-text">{q.questionText}</h2></Card><Card>{answered?<><div className="section-heading"><h2>Your answer</h2><Badge tone="success"><CheckCircle2 size={12} className="mr-1"/>Submitted</Badge></div><p className="prose-text">{q.userAnswer}</p></>:<form onSubmit={submit}><div className="field"><label htmlFor="interview-answer">Your answer</label><textarea id="interview-answer" className="answer-area" placeholder="Explain your approach, share an example, and make your thinking clear…" value={answerText} onChange={e=>setAnswerText(e.target.value)} disabled={submitting} aria-describedby="answer-help"/><small id="answer-help">Take your time. Your answer is saved when you submit it.</small></div><div className="answer-toolbar"><span className="muted text-xs">{answerText.length.toLocaleString()} characters</span><div className="flex flex-wrap gap-2"><ButtonLink variant="ghost" to="/interviews">Save & Exit</ButtonLink><Button type="submit" busy={submitting} disabled={!answerText.trim()}>{submitting?'Evaluating answer…':'Submit answer'}<Send size={15}/></Button></div></div></form>}</Card>{answered&&<Card><Evaluation evaluation={q.evaluation}/></Card>}{answered&&<div className="form-actions"><p>Review your feedback before continuing.</p>{index<questions.length-1?<Button onClick={()=>{setIndex(i=>i+1);setAnswerText('');setError('');}}>Next question<ArrowRight size={16}/></Button>:<Button busy={completing} onClick={finish}>{completing?'Preparing your results…':'Finish Interview'}<CheckCircle2 size={16}/></Button>}</div>}</div></div>;
}
