import { useCallback, useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-react';
import * as interviewService from '../../services/interviewService';
import { Card, PageHeader, ButtonLink, LoadingState, ErrorState, Badge, FeedbackList, Evaluation, SectionHeader } from '../../components/ui';
export default function InterviewResults() {
  const {sessionId}=useParams(),navigate=useNavigate();
  const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await interviewService.getSession(sessionId);if(data.status!=='completed'){navigate(`/interview/${sessionId}`,{replace:true});return;}setSession(data);}catch{setError('We couldn’t load your interview results.');}finally{setLoading(false);}},[sessionId,navigate]);
  useEffect(()=>{load();},[load]);
  if(loading)return <LoadingState label="Loading your interview results…"/>;
  if(error||!session)return <ErrorState message={error||'Session not found'} retry={load}/>;
  const feedback=session.overallFeedback;
  return <div className="narrow"><PageHeader eyebrow="REFLECT. REFINE. REPEAT." title="Interview results" description="Turn your feedback into a clear plan for the next session." action={<ButtonLink variant="outline" to="/dashboard"><ArrowLeft size={15}/>Dashboard</ButtonLink>}/><div className="stack"><Card className="result-hero"><div className="score-circle"><strong>{session.overallScore ?? '—'}</strong><span>OUT OF 10</span></div><div><div className="chips mb-3"><Badge tone="success"><CheckCircle2 size={12} className="mr-1"/>Interview complete</Badge></div><h2>{session.targetRole}</h2><p className="muted text-sm mt-1">One more session. One step closer to your next opportunity.</p><div className="result-meta">{[['Mode',session.interviewMode],['Difficulty',session.difficulty],['Questions',session.questions.length],['Type',session.interviewType]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></Card>
  {feedback&&<Card><SectionHeader title="Overall feedback" description="The key takeaways from your interview."/><p className="prose-text mb-6">{feedback.summary}</p><div className="grid-two"><FeedbackList title="Strengths" items={feedback.strengths} tone="positive"/><FeedbackList title="Areas to improve" items={feedback.weaknesses} tone="attention"/><FeedbackList title="Missing concepts" items={feedback.missingConcepts}/><FeedbackList title="Improvement priorities" items={feedback.improvementPriorities} ordered/><div className="full"><FeedbackList title="Next steps" items={feedback.nextSteps} ordered/></div></div></Card>}
  <section><SectionHeader title="Question review" description="Open a question to revisit your answer and detailed feedback."/><div className="stack">{session.questions.map((q,i)=><details className="review" key={q._id}><summary><div className="review-title"><small>QUESTION {i+1} · {q.topic}</small><strong>{q.questionText}</strong></div><Badge tone="primary">{q.evaluation?.score ?? '—'} / 10</Badge></summary><div className="review-body"><div className="inset"><h3>Your answer</h3><p className="prose-text">{q.userAnswer}</p></div><Evaluation evaluation={q.evaluation}/></div></details>)}</div></section><div className="form-actions"><p>Take your next step when you're ready.</p><ButtonLink to="/interview/setup">Start another interview<ArrowRight size={16}/></ButtonLink></div></div></div>;
}
