import { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { Play, Target, TrendingUp, Sparkles, CheckCircle2, CircleAlert, ArrowRight } from 'lucide-react';
import * as interviewService from '../../services/interviewService';
import * as profileService from '../../services/profileService';
import * as dashboardService from '../../services/dashboardService';
import { Card, PageHeader, SectionHeader, Button, ButtonLink, ErrorState } from '../../components/ui';
const modes = [['Normal','Normal Interview','A balanced interview for your role and experience.',Play],['Focused Practice','Focused Practice','Work on one topic with deliberate practice.',Target],['Adaptive Practice','Adaptive Practice','Practice around your past performance.',TrendingUp],['Personalized','Personalized Interview','Connect your resume, target job and skill gaps.',Sparkles]];
export default function InterviewSetup() {
  const navigate=useNavigate(), location=useLocation();
  const [loading,setLoading]=useState(false),[error,setError]=useState(''),[profile,setProfile]=useState(null),[stats,setStats]=useState(null),[readinessLoading,setReadinessLoading]=useState(true),[readinessError,setReadinessError]=useState(false);
  const [formData,setFormData]=useState({targetRole:'',interviewType:'Technical',experienceLevel:'Entry Level',difficulty:'Medium',techStack:'',interviewMode:location.state?.interviewMode || 'Normal',focusTopic:location.state?.focusTopic || '',questionCount:3});
  const loadReadiness = async () => { setReadinessLoading(true); setReadinessError(false); try { const [p,s]=await Promise.all([profileService.getProfile(),dashboardService.getStats()]); setProfile(p); setStats(s); } catch { setReadinessError(true); } finally {setReadinessLoading(false);} };
  useEffect(()=>{loadReadiness();},[]);
  const change=e=>setFormData({...formData,[e.target.name]:e.target.name==='questionCount'?parseInt(e.target.value,10):e.target.value});
  const isResumeReady=!!profile?.resume?.analyzedAt,isJdReady=!!profile?.jobDescription?.analyzedAt,isMatchReady=!!profile?.matchAnalysis?.analyzedAt;
  const isPersonalizedReady=isResumeReady&&isJdReady&&isMatchReady;
  const submit=async e=>{e.preventDefault();if(formData.interviewMode==='Personalized'&&!isPersonalizedReady){setError('Please complete all required profile analysis before starting a Personalized Interview.');return;}setLoading(true);setError('');try{const session=await interviewService.createSession({...formData,techStack:formData.techStack.split(',').map(s=>s.trim()).filter(Boolean)});navigate(`/interview/${session._id}`);}catch(err){setError(err.response?.data?.message || 'Failed to create interview session');}finally{setLoading(false);}};
  const select=(name,label,options)=><div className="field"><label htmlFor={name}>{label}</label><select id={name} name={name} value={formData[name]} onChange={change}>{options.map(o=><option key={o} value={o}>{name==='questionCount'?`${o} questions`:o}</option>)}</select></div>;
  return <div className="narrow"><PageHeader eyebrow="MAKE YOUR NEXT SESSION COUNT" title="Set up your interview" description="Choose your role, set your focus, and make practice personal."/>{error&&<ErrorState message={error}/>}<form onSubmit={submit} className="stack">
    <Card><SectionHeader title={<><span className="form-section-number">01</span>Interview basics</>} description="Tell us about the opportunity you're preparing for."/><div className="form-grid"><div className="field full"><label htmlFor="targetRole">Target role</label><input id="targetRole" name="targetRole" required value={formData.targetRole} onChange={change} placeholder="e.g. Frontend Developer"/></div>{select('interviewType','Interview type',['Technical','Behavioral','Project-Based','Mixed'])}{select('experienceLevel','Experience level',['Student','Entry Level','1-3 Years','3+ Years'])}</div></Card>
    <Card><SectionHeader title={<><span className="form-section-number">02</span>Technical context</>} description="Set a challenge that feels right for you."/><div className="form-grid">{select('difficulty','Difficulty',['Easy','Medium','Hard'])}{select('questionCount','Question count',[3,5,10])}<div className="field full"><label htmlFor="techStack">Tech stack</label><input id="techStack" name="techStack" value={formData.techStack} onChange={change} placeholder="React, Node.js, TypeScript" aria-describedby="stack-help"/><small id="stack-help">Separate technologies with commas.</small></div></div></Card>
    <Card><fieldset><legend className="mb-2"><h2><span className="form-section-number">03</span>Choose your practice mode</h2></legend><p className="muted text-sm mb-5">Different ways to prepare. One clear goal: progress.</p><div className="mode-grid">{modes.map(([value,title,description,Icon])=><label className="mode-option" key={value}><input type="radio" name="interviewMode" value={value} checked={formData.interviewMode===value} onChange={change}/><Icon size={20} aria-hidden="true"/><span><strong>{title}</strong><small>{description}</small></span></label>)}</div></fieldset>
      {formData.interviewMode==='Focused Practice'&&<div className="field mt-6"><label htmlFor="focusTopic">Focus topic</label><input id="focusTopic" name="focusTopic" required value={formData.focusTopic} onChange={change} placeholder="e.g. JavaScript Closures"/></div>}
      {formData.interviewMode==='Adaptive Practice'&&<div className="inset mt-6"><h3>Practice informed by your progress</h3><p className="muted text-sm mt-2">Your completed interviews help identify areas to revisit. Your selected role, difficulty and tech stack still guide the session.</p></div>}
      {formData.interviewMode==='Personalized'&&<div className="inset mt-6"><SectionHeader title="Personalized readiness" description="Your context helps make questions relevant."/>{readinessLoading?<p role="status" className="muted">Checking your preparation context…</p>:readinessError?<ErrorState message="Couldn’t check your readiness." retry={loadReadiness}/>:<div className="readiness">{[['Resume uploaded',!!profile?.resume?.rawText],['Resume analyzed',isResumeReady],['Job description analyzed',isJdReady],['Resume-to-JD match ready',isMatchReady]].map(([label,ready])=><div key={label} className={`readiness-row ${ready?'':'pending'}`}>{ready?<CheckCircle2 size={18}/>:<CircleAlert size={18}/>}<span>{label} — <strong>{ready?'Ready':'Action needed'}</strong></span></div>)}<p className="muted text-sm">{stats?.overview?.totalInterviews || 0} completed interviews in your history · optional</p>{!isPersonalizedReady&&<ButtonLink variant="outline" to="/profile#resume">Complete your profile<ArrowRight size={15}/></ButtonLink>}</div>}</div>}
    </Card><div className="form-actions"><p>Your answers are saved when you submit them.</p><Button type="submit" busy={loading} disabled={formData.interviewMode==='Personalized'&&!isPersonalizedReady}>{loading?'Creating interview…':'Start Interview'}<ArrowRight size={16}/></Button></div>
  </form></div>;
}
